Calendar/config/routes.rb
Rails.application.routes.draw do
  resources :events do
    get 'subscribe'
    get 'unsubscribe'
  end

  devise_for :users
  resources :users, shallow: true do
    resources :events
  end

  root to: "events#index"
    get '/profile', to: 'users#show'
    get '/subscribed_events', to: 'events#subscribed_events'
end

Calendar/app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, :start_time, presence: true
  has_many :subscriptions
  belongs_to :user

end

Calendar/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

Calendar/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :full_name, presence: true
  has_many :subscriptions
  has_many :events, through: :subscriptions

end

Calendar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization

  protect_from_forgery with: :exception

  responders :flash
  respond_to :html

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

end

Calendar/app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper do
      def current_user
        super.decorate if user_signed_in?
      end
    end
  end

  private

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

Calendar/app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    redirect_to(root_path)
  end
end

Calendar/app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  expose(:user)

  def index
  end

  def show
  end
end

Calendar/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  respond_to :html
  helper EventsHelper

  def index
    @events = Event.where("kind = ? or user_id = ?", "global", current_user.id)
  end

  def show
    @policy = event_policy(@event)
  end

  def edit
  end

  def new
    @event = current_user.events.new
  end

  def subscribe
    @event = Event.find(params[:event_id])
    if !event_policy(@event).subscribed?
      @subscription = subscribe_create(@event)
      redirect_to event_path(@event), notice: 'You was successfully subscribed on this event'
    else
      redirect_to event_path(@event), notice: 'You are already subscribed on this event'
    end
  end

  def unsubscribe
    @event = Event.find(params[:event_id])
    if !event_policy(@event).subscribed?
      redirect_to event_path(@event), notice: 'You are not subscribed on this event yet'
    else
      @subscription = Subscription.find_by(user: current_user, event: @event)
      @subscription.destroy
      redirect_to event_path(@event), notice: 'You were unsubscribed from this event'
    end
  end

  def create
    @event = current_user.events.create(event_params)
    @event.user = current_user
    if @event.save
      redirect_to events_url, notice: 'Event was successfully created.'
    else
      redirect_to new_event_url, notice: 'Error'
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit, notice: 'Error'
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, notice: 'Event was successfully deleted'
  end

  def subscribed_events
    @events = current_user.events
  end

  private
  def event_params
    params.require(:event).permit(:name, :start_time, :user_id, :kind)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def subscribe_create(event)
    @subscription = Subscription.create(user: current_user, event: event)
  end

  def event_policy(event)
    @policy = EventPolicy.new(current_user, event)
  end
end

Calendar/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def index
  end


end

Calendar/app/helpers/events_helper.rb
module EventsHelper
  def events_ajax_previous_link
    ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
    end

  def events_ajax_next_link
    ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
  end
end

Calendar/app/views/application/_footer.html.slim
footer.row
  .columns
    p &copy; Arthur Galiullin #{Time.zone.today.year}

Calendar/app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(data-alert class="alert-box #{type}" tabindex="0" aria-live="assertive" role="alertdialog")
    = content
    button.close(tabindex="0" aria-label="Close Alert") &times;

Calendar/app/views/application/_navigation.html.slim
nav.top-bar( data-topbar )

  ul.title-area
    li.name
      h1 = link_to "Cool Calendar", root_path
    li.toggle-topbar
      a(href="#")
        i.fi-list

  section.top-bar-section
    = render "navigation_main"
    = render "navigation_user"

Calendar/app/views/application/_navigation_main.html.slim
ul.left
  - if user_signed_in?
    - if request.env['PATH_INFO'] == '/subscribed_events'
      = active_link_to "All events", events_path, active: :exclusive, wrap_tag: :li
    - else
      = active_link_to "Subscribed events", subscribed_events_path, active: :exclusive, wrap_tag: :li

Calendar/app/views/application/_navigation_user.html.slim
ul.right
  - if user_signed_in?
    li.has-dropdown
      a.user-dropdown(href="#") = current_user.full_name_with_email
      ul.dropdown
        new_user_registration_path
        li
          a href = edit_user_registration_path
            | Edit profile
        li
          a href = destroy_user_session_path
            | Sign out
  - else
    = active_link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = active_link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li

Calendar/app/views/events/_calendar.html.slim
= month_calendar events: @events, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, events|
  = date
  br
  - events.each do |event|
    = link_to event.name, event
    br
= link_to "Create new event", new_event_path

Calendar/app/views/events/_form.html.slim
= simple_form_for(@event) do |f|
  .form-inputs
    = f.input :name
    = f.input :start_time
    = f.input :kind, :collection => ['global', 'private'], :include_blank => false

  .form-actions
    = f.button :submit
    '  or
    = link_to 'Back', :back

Calendar/app/views/events/_list.html.slim
- @events.each do |event|
  = event.name
  '
  = event.start_time
  br

Calendar/app/views/events/edit.html.slim
= render 'form'

Calendar/app/views/events/index.html.slim
.row
  .columns
    = render partial: "calendar", locals: {events: @events}
    br
    = link_to "Subscribed events", subscribed_events_path
    br

Calendar/app/views/events/index.js.slim
+$("#events_calendar").html("<%= escape_javascript render(partial: "calendar", locals: {events: @events}) %>");

Calendar/app/views/events/new.html.slim
= render 'form'

Calendar/app/views/events/show.html.slim
- if @policy.private?
  - if !@policy.own?
    - controller.redirect_to root_path, notice: 'You are not allowed to see this event'
.show-item
  .well.event.form-horizontal
    .control-group
      label.control-label
        | Name
      .controls
        .input-xlarge.uneditable-input.string.span7
          = @event.name
    .control-group
      label.control-label
        | Start time
      .controls
        .input-xlarge.uneditable-input.datetime.span7
          = @event.start_time
  .form-actions
    - if @policy.own?
      = link_to(edit_event_path(@event), class: 'btn btn-primary') do
        i.fi-pencil
        | Edit
    '  or
    = link_to 'Back', :back
    - if @policy.own?
      '  or
      = link_to 'Delete', event_path(@event), method: 'delete'
    br
    - if !@policy.subscribed?
      = link_to 'Subscribe', event_subscribe_path(@event)
    - else
      = link_to 'Unsubscribe', event_unsubscribe_path(@event)
script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-57554f0223467914"

Calendar/app/views/events/subscribed_events.html.slim
.row
  .columns
    = month_calendar events: @events do |date, meetings|
      = date
      - meetings.each do |meeting|
        = link_to meeting.name, meeting
    = link_to "Create new event", new_event_path
    br
    = link_to "All events", events_path

Calendar/app/views/layouts/application.html.slim
doctype html

html class="no-js" lang="en"

  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="NOODP,NOYDIR"

    = metamagic site: "Cool Calendar", title: %i(title site), separator: " - "
    = csrf_meta_tags

    = stylesheet_link_tag :application

    = javascript_include_tag "vendor/modernizr"

    = javascript_tag "window.App = {}"

    == analytics_init if GA.tracker

  body
    #root
      = render "navigation"
      = render "messages"

      = yield

    = render "footer"

    javascript:
      App.currentUserData = #{{current_user.to_json}};

    = javascript_include_tag :application

Calendar/app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day)) %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day)) %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

Calendar/app/views/simple_calendar/_month_calendar.html.slim
.simple-calendar
  .action_buttons
    = link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day))
    '
    = I18n.t("date.month_names")[start_date.month]
    = start_date.year
    '
    = link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day))
  table.table.table-striped
    thead
      tr
        - date_range.slice(0, 7).each do |day|
          th
            .week_days
              = I18n.t("date.abbr_day_names")[day.wday][0..3]
    tbody
      - date_range.each_slice(7) do |week|
        tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml do
                  - block.call day.to_s[8..9], sorted_events.fetch(day, [])
              - else
                - block.call day.to_s[8..9], sorted_events.fetch(day, [])

Calendar/app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", url_for(params.merge(start_date: date_range.first - 1.day)) %>
  Week <%= start_date.strftime("%U").to_i %>
  <%= link_to "Next", url_for(params.merge(start_date: date_range.last + 1.day)) %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

Calendar/app/views/users/shared/_links.html.slim
h6 Anything else?
ul.links
  - if controller_name != "sessions"
    li = link_to "Sign in", new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != "registrations"
    li = link_to "Create a new account", new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != "passwords"
    li = link_to "Forgot your password?", new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != "confirmations"
    li = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks"
    li = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)

Calendar/app/views/users/show.html.slim
= user.full_name